config/routes.rb
Rails.application.routes.draw do
  scope :monitoring do
    require 'sidekiq/web'
    mount Sidekiq::Web, at: '/jobs'
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

  devise_for :users

  resources :dashboard, only: :index
  root to: 'dashboard#index'
  resources :users, only: :index do
    member do
      get :edit_profile
      post :update_profile
    end
  end

  authenticated :user do
    namespace :admin_panel do
      root to: "members#index"

      resources :members, only: %i[index show destroy]
      resources :events do
        member do
          get :export_rsvp
        end
      end
      resources :posts, only: %i[destroy]
      resources :reports, only: %i[index destroy] do
        member do
          get :post_report
          get :member_report
          get :close_reports
        end
      end
      resources :colleges, only: %i[index new create edit update destroy]
    end
  end

  %w(admin instructor student).each do |user_type|
    resources user_type.pluralize.to_sym, controller: "users", type: user_type.camelize, only: :index
  end

  get 'terms_and_conditions', to: 'public#terms_and_conditions', as: 'terms_and_conditions'

  mount Rswag::Api::Engine => '/api-docs'
  mount Rswag::Ui::Engine => '/api-docs'

  devise_for :members, controllers: { confirmations: 'members/confirmations', passwords: 'members/passwords' }, skip: [:sessions, :registrations]
  resources :members, only: [:index,:show,:destroy] do
    member do
      get :password_change_success
    end

    collection do
      get :confirm_notice
    end
  end

  namespace :api do
    namespace :v1 do
      devise_for(
        :members,
        controllers: { sessions: 'api/v1/devise/sessions', registrations: 'api/v1/devise/registrations' },
        path_names: { sign_in: :login },
        defaults: { format: :json },
        skip: [:confirmations, :passwords]
      )

      resources :accounts, only: %i[] do
        collection do
          get :resend_confirmation
          post :reset_password_link
          get :confirmation_status
          post :change_password
          get :suggestions
        end
      end

      resources :skills, only: %i[index]
      resource :onboarding, only: %i[create]
      resources :members, only: %i[index] do
        get :follow
        get :unfollow

        collection do
          post :bulk_follow
          get :followers_list
          delete :logout
        end

        member do
          get :profile
        end
      end

      resources :posts, only: %i[index create show destroy] do
        resources :comments, only: %i[index create destroy]
        resource :likes, only: %i[create destroy]
        resource :shares, only: %i[create destroy]
      end

      resources :block_members, only: %i[create] do
        delete :destroy
      end
      resources :member_reports, only: %i[create] do
        delete :destroy
      end
      resources :post_reports, only: %i[create] do
        delete :destroy
      end
      resources :groups, only: %i[index create update show destroy]
      resources :feeds, only: %i[index]
      resources :groups, only: %i[create update show destroy] do
        member do
          post :leave_group
          get '/read_conversation/:member_id', to: 'groups#read_conversation', as: :read_conversation
        end
      end

      resources :notifications, only: %i[index] do
        member do
          get :read
        end
      end
      resources :rsvps, only: %i[create destroy], param: :event_id
      resources :events, only: %i[index show]
      resources :devices, only: %i[create]
      resources :colleges, only: %i[index]
    end
  end

  post :talkjs, to: 'webhooks#talkjs'
end

app/models/user.rb
class User < ApplicationRecord
  has_person_name

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :invitable

  validates :first_name, :last_name, presence: true

  has_one_attached :avatar

  def admin?
    false
  end

  def student?
    false
  end

  def instructor?
    false
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def index
    @users = User.all
  end

  def edit_profile; end

  def update_profile
    @user.update(user_params)
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :bio, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def show_avatar(user)
    if user.avatar.attached?
      image_tag(url_for(user.avatar), height: 30, class: 'd-inline-block align-top')
    else
      "<i class='material-icons'>person</i>".html_safe
    end
  end
end

app/views/users/edit_profile.html.erb
<div class="container-fluid mt-4">
  <h4 class="mb-3"><%= t('custom.pages.user.edit.heading') %></h4>
  <%= form_with(scope: :user, url: update_profile_user_path, id: 'user_form') do |form| %>
    <div class="form-row">
      <div class="form-group col-6">
        <%= form.label :first_name %>
        <%= form.text_field :first_name, class: 'form-control', placeholder: true %>
      </div>
      <div class="form-group col-6">
        <%= form.label :last_name %>
        <%= form.text_field :last_name, class: 'form-control', placeholder: true %>
      </div>
    </div>
    <div class="form-group">
      <%= form.label :bio %>
      <%= form.text_area :bio, class: 'form-control', placeholder: true %>
    </div>
    <div class="form-group">
      <%= form.label :avatar %>
      <%= form.file_field :avatar, class: 'form-control', placeholder: true %>
    </div>
    <hr class="mt-4 mb-4"/>
    <div class="text-left">
      <%= link_to t('custom.buttons.back'), root_path, class: 'btn btn-outline-primary' %>
      <%= form.submit t('custom.pages.user.edit.submit'), class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col">
      <h1 class="display-4 mb-4">Users</h1>
      <table class="table table-striped">
        <thead>
        <tr>
          <th scope="col">Email</th>
        </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.email %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/update_profile.js.erb
Quadio.Utility.showFormError('#user_form', 'user', <%= @user.errors.messages.to_json.html_safe %>);
<% if @user.errors.blank? %>
  Quadio.Utility.toastSuccess('<%= t('custom.messages.user.update') %>');
<% end %>