config/routes.rb
Rails.application.routes.draw do
  scope :monitoring do
    require 'sidekiq/web'
    mount Sidekiq::Web, at: '/jobs'
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

  devise_for :users

  resources :dashboard, only: :index
  root to: 'dashboard#index'
  resources :users, only: :index do
    member do
      get :edit_profile
      post :update_profile
    end
  end

  authenticated :user do
    namespace :admin_panel do
      root to: "members#index"

      resources :members, only: %i[index show destroy]
      resources :events do
        member do
          get :export_rsvp
        end
      end
      resources :posts, only: %i[destroy]
      resources :reports, only: %i[index destroy] do
        member do
          get :post_report
          get :member_report
          get :close_reports
        end
      end
      resources :colleges, only: %i[index new create edit update destroy]
    end
  end

  %w(admin instructor student).each do |user_type|
    resources user_type.pluralize.to_sym, controller: "users", type: user_type.camelize, only: :index
  end

  get 'terms_and_conditions', to: 'public#terms_and_conditions', as: 'terms_and_conditions'

  mount Rswag::Api::Engine => '/api-docs'
  mount Rswag::Ui::Engine => '/api-docs'

  devise_for :members, controllers: { confirmations: 'members/confirmations', passwords: 'members/passwords' }, skip: [:sessions, :registrations]
  resources :members, only: [:index,:show,:destroy] do
    member do
      get :password_change_success
    end

    collection do
      get :confirm_notice
    end
  end

  namespace :api do
    namespace :v1 do
      devise_for(
        :members,
        controllers: { sessions: 'api/v1/devise/sessions', registrations: 'api/v1/devise/registrations' },
        path_names: { sign_in: :login },
        defaults: { format: :json },
        skip: [:confirmations, :passwords]
      )

      resources :accounts, only: %i[] do
        collection do
          get :resend_confirmation
          post :reset_password_link
          get :confirmation_status
          post :change_password
          get :suggestions
        end
      end

      resources :skills, only: %i[index]
      resource :onboarding, only: %i[create]
      resources :members, only: %i[index] do
        get :follow
        get :unfollow

        collection do
          post :bulk_follow
          get :followers_list
          delete :logout
        end

        member do
          get :profile
        end
      end

      resources :posts, only: %i[index create show destroy] do
        resources :comments, only: %i[index create destroy]
        resource :likes, only: %i[create destroy]
        resource :shares, only: %i[create destroy]
      end

      resources :block_members, only: %i[create] do
        delete :destroy
      end
      resources :member_reports, only: %i[create] do
        delete :destroy
      end
      resources :post_reports, only: %i[create] do
        delete :destroy
      end
      resources :groups, only: %i[index create update show destroy]
      resources :feeds, only: %i[index]
      resources :groups, only: %i[create update show destroy] do
        member do
          post :leave_group
          get '/read_conversation/:member_id', to: 'groups#read_conversation', as: :read_conversation
        end
      end

      resources :notifications, only: %i[index] do
        member do
          get :read
        end
      end
      resources :rsvps, only: %i[create destroy], param: :event_id
      resources :events, only: %i[index show]
      resources :devices, only: %i[create]
      resources :colleges, only: %i[index]
    end
  end

  post :talkjs, to: 'webhooks#talkjs'
end

app/views/shared/_error.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <%= content_tag :li, [msg.html_safe, '.'].join %>
      <% end %>
    </ul>

    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container text-center">
    <span class="text-muted">Quadio @ <%= Time.zone.now.year %></span>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div id="sidebar-wrapper">
  <div class="sidebar-logo">
    <%= link_to admin_panel_root_path, class: 'navbar-brand' do %>
      Quadio
    <% end %>
  </div>

  <div class="list-group list-group-flush">
    <ul>
      <% if can? [:manage], Member %>
        <li>
          <%= link_to admin_panel_members_path do %>
            <i class="fas fa-users"></i>
            <span>Users</span>
          <% end %>
        </li>
      <% end %>

      <% if can? [:manage], College %>
        <li>
          <%= link_to admin_panel_colleges_path do %>
            <i class="fas fa-network-wired"></i>
            <span>Colleges</span>
          <% end %>
        </li>
      <% end %>

      <% if can? [:manage], MemberReport %>
        <li>
          <%= link_to admin_panel_reports_path do %>
            <i class="fas fa-users"></i>
            <span>
              Reports
              <% if @reports_count.present? %>
                <span class="count"><%= @reports_count %></span>
              <% end %>
            </span>
          <% end %>
        </li>
      <% end %>

      <% if can? [:manage], Event %>
        <li>
          <%= link_to admin_panel_events_path do %>
          <i class="fas fa-calendar-check"></i>
            <span>Events</span>
          <% end %>
        </li>
      <% end %>

      <li class="bottom-fixed">
        <%= link_to terms_and_conditions_path, target: '_blank' do %>
          <i class= "margin-bottom fa fa-gavel"></i>
          <span>
            Terms and conditions
          </span>
        <% end %>

        <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fas fa-sign-out-alt"></i>
          <span>
            <%= t('custom.header.navbar.links.logout') %>
          </span>
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_notice.html.erb
<% if flash[:error] -%>
  <p class='d-none error-mg'><%= h flash[:error] %></p>
<% end -%>
<% if flash[:alert] -%>
  <p class='d-none alert-mg'><%= h flash[:alert] %></p>
<% end -%>
<% if flash[:notice] -%>
  <p class='d-none notice-mg'><%= h flash[:notice] %></p>
<% end -%>