config/routes.rb
Rails.application.routes.draw do
  scope :monitoring do
    require 'sidekiq/web'
    mount Sidekiq::Web, at: '/jobs'
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

  devise_for :users

  resources :dashboard, only: :index
  root to: 'dashboard#index'
  resources :users, only: :index do
    member do
      get :edit_profile
      post :update_profile
    end
  end

  authenticated :user do
    namespace :admin_panel do
      root to: "members#index"

      resources :members, only: %i[index show destroy]
      resources :events do
        member do
          get :export_rsvp
        end
      end
      resources :posts, only: %i[destroy]
      resources :reports, only: %i[index destroy] do
        member do
          get :post_report
          get :member_report
          get :close_reports
        end
      end
      resources :colleges, only: %i[index new create edit update destroy]
    end
  end

  %w(admin instructor student).each do |user_type|
    resources user_type.pluralize.to_sym, controller: "users", type: user_type.camelize, only: :index
  end

  get 'terms_and_conditions', to: 'public#terms_and_conditions', as: 'terms_and_conditions'

  mount Rswag::Api::Engine => '/api-docs'
  mount Rswag::Ui::Engine => '/api-docs'

  devise_for :members, controllers: { confirmations: 'members/confirmations', passwords: 'members/passwords' }, skip: [:sessions, :registrations]
  resources :members, only: [:index,:show,:destroy] do
    member do
      get :password_change_success
    end

    collection do
      get :confirm_notice
    end
  end

  namespace :api do
    namespace :v1 do
      devise_for(
        :members,
        controllers: { sessions: 'api/v1/devise/sessions', registrations: 'api/v1/devise/registrations' },
        path_names: { sign_in: :login },
        defaults: { format: :json },
        skip: [:confirmations, :passwords]
      )

      resources :accounts, only: %i[] do
        collection do
          get :resend_confirmation
          post :reset_password_link
          get :confirmation_status
          post :change_password
          get :suggestions
        end
      end

      resources :skills, only: %i[index]
      resource :onboarding, only: %i[create]
      resources :members, only: %i[index] do
        get :follow
        get :unfollow

        collection do
          post :bulk_follow
          get :followers_list
          delete :logout
        end

        member do
          get :profile
        end
      end

      resources :posts, only: %i[index create show destroy] do
        resources :comments, only: %i[index create destroy]
        resource :likes, only: %i[create destroy]
        resource :shares, only: %i[create destroy]
      end

      resources :block_members, only: %i[create] do
        delete :destroy
      end
      resources :member_reports, only: %i[create] do
        delete :destroy
      end
      resources :post_reports, only: %i[create] do
        delete :destroy
      end
      resources :groups, only: %i[index create update show destroy]
      resources :feeds, only: %i[index]
      resources :groups, only: %i[create update show destroy] do
        member do
          post :leave_group
          get '/read_conversation/:member_id', to: 'groups#read_conversation', as: :read_conversation
        end
      end

      resources :notifications, only: %i[index] do
        member do
          get :read
        end
      end
      resources :rsvps, only: %i[create destroy], param: :event_id
      resources :events, only: %i[index show]
      resources :devices, only: %i[create]
      resources :colleges, only: %i[index]
    end
  end

  post :talkjs, to: 'webhooks#talkjs'
end

app/models/event.rb
class Event < ApplicationRecord
  has_one_attached :cover
  has_many :rsvps, dependent: :destroy
  has_many :members, through: :rsvps

  validates :title, :start_at, presence: true
  validate  :ensure_start_date

  def date_range
    return start_at.strftime("%B %d, %Y") if end_at.blank?

    "#{start_at.strftime("%B %d")} - #{end_at.strftime("%B %d, %Y")}"
  end

  def ensure_start_date
    return if start_at.blank? || end_at.blank?

    errors.add(:start_at, "Start date can't be greater than end date.") if start_at > end_at
  end
end

app/controllers/admin_panel/base_controller.rb
module AdminPanel
  class BaseController < ApplicationController
    before_action :reports_count

    def reports_count
      @reports_count = MemberReport.open.count + PostReport.open.count
    end
  end
end

app/controllers/admin_panel/colleges_controller.rb
module AdminPanel
  class CollegesController < BaseController
    before_action :set_college, only: %i[edit update destroy]

    def index
      @colleges = College.latest.includes(:college_domains)
      @colleges = FilterCollegeQuery.new(@colleges).call(params)
      @colleges = @colleges.page(page).per(per_page)
    end

    def new
      @college = College.new
    end

    def create
      @college = College.new college_params

      flash[:notice] = 'College is successfully created.' if @college.save
    end

    def edit; end

    def update
      flash[:notice] = 'College is successfully updated.' if @college.update(college_params)
    end

    def destroy
      if @college.destroy
        flash[:notice] = 'This College destroyed successfully'
      else
        flash[:alert] = @college.errors.full_messages.to_sentence
      end

      redirect_to admin_panel_colleges_path
    end

    private

    def set_college
      @college = College.find(params[:id])
    end

    def college_params
      params.require(:college).permit(:name, college_domains_attributes: [:id, :domain, :_destroy])
    end
  end
end

app/controllers/admin_panel/events_controller.rb
module AdminPanel
  class EventsController < BaseController
    before_action :set_event, only: %i[edit update destroy]

    def index
      @upcoming_events =
        Event.where('DATE(start_at) >= ?', Time.zone.now.to_date).order(start_at: :asc).page(params[:upcoming_events_page]).per(per_page)

      @historical_events =
        Event.where('DATE(start_at) < ?', Time.zone.now.to_date).order(start_at: :asc).page(params[:historical_events_page]).per(per_page)
    end

    def new
      @event = Event.new

      respond_to do |format|
        format.js
      end
    end

    def create
      @event = Event.new event_params

      respond_to do |format|
        format.js
      end
    end

    def edit; end

    def update
      @event.update(event_params)

      respond_to do |format|
        format.js
      end
    end

    def destroy
      respond_to do |format|
        format.js
      end
    end

    def export_rsvp
      @event = Event.includes(rsvps: :member).find params[:id]

      send_data ExportRsvp.new(@event).call, filename: 'rsvps.csv'
    end

    private

    def set_event
      @event = Event.find params[:id]
    end

    def event_params
      params.require(:event).permit(:title, :description, :price, :location, :start_at, :end_at, :cover)
    end
  end
end

app/controllers/admin_panel/members_controller.rb
module AdminPanel
  class MembersController < BaseController
    before_action :set_member, only: %i[show destroy]

    def index
      @members = FilterMembersQuery.new(Member).call(params)
      @members = @members.page(page).per(per_page)
    end

    def show; end

    def destroy
      if @member.destroy
        flash[:notice] = 'Member deleted successfully.'
      else
        flash[:alert]  = @member.errors.full_messages.to_sentence
      end

      redirect_to admin_panel_members_path
    end

    private

    def set_member
      @member = Member.find params[:id]
    end
  end
end

app/controllers/admin_panel/posts_controller.rb
module AdminPanel
  class PostsController < BaseController
    def destroy
      @post = Post.find(params[:id])

      if @post.destroy
        flash[:notice] = 'Post is successfully deleted.'
      else
        flash[:alert] = @post.errors.full_messages.to_sentence
      end

      redirect_to admin_panel_reports_path
    end
  end
end

app/controllers/admin_panel/reports_controller.rb
module AdminPanel
  class ReportsController < BaseController
    def index
      @post_reports = PostReport.open.includes(:reporter, post: [:creator]).page(params[:post_report_page]).per(per_page)
      @member_reports = MemberReport.open.includes(:reporter, :reported).page(page).per(per_page)
    end

    def post_report
      @post_report = PostReport.find params[:id]
    end

    def close_reports
      klass = "#{params[:klass]}Report".constantize
      @report = klass.find params[:id]

      if @report.update_column(:status, klass::STATUSES[:close])
        flash[:notice] = "#{params[:klass]} Report is successfully closed."
      else
        flash[:alert] = @report.errors.full_messages.to_sentence
      end

      redirect_to admin_panel_reports_path
    end

    def member_report
      @member_report = MemberReport.find params[:id]
    end
  end
end

app/controllers/api/v1/events_controller.rb
module Api
  module V1
    class EventsController < SecureController
      before_action :set_event, only: %i[show]

      def index
        events = Event.where('DATE(start_at) >= ?', Time.zone.now.to_date).includes(:members).order(start_at: :asc).with_attached_cover
        @meta, @events = paginate events
      end

      def show; end

      private

      def set_event
        @event = Event.find(params[:id])
      end
    end
  end
end

app/views/admin_panel/events/_event.html.erb
<tr id="<%= dom_id(event) %>">
  <th scope="row"><%= event.id %></th>
  <td><%= event.title %></td>
  <td><%= event.start_at.strftime("%d %B %Y") %></td>
  <td><%= event.price %></td>
  <td class="icon">
    <%= link_to export_rsvp_admin_panel_event_path(event), class: 'ml-1 mr-1', data: { toggle: 'tooltip' }, title: 'Export RSVPs' do %>
      <i class="fas fa-file-export"></i>
    <% end %>

    <%= link_to edit_admin_panel_event_path(event), class: 'ml-1 mr-1', remote: true, data: { toggle: 'tooltip' }, title: 'Edit Event' do %>
      <i class="fas fa-edit"></i>
    <% end %>

    <%= link_to admin_panel_event_path(event), class: 'ml-1 mr-1', method: :delete, remote: true, data: { confirm:  'Are you sure, you want to delete event?', toggle: 'tooltip' }, title: 'Delete Event' do %>
      <i class="fas fa-trash"></i>
    <% end %>
  </td>
</tr>

app/views/admin_panel/events/_form.html.erb
<div class="modal-dialog">
  <%= form_for [:admin_panel, event], remote: true do |f| %>
    <div class="modal-content">
      <div class="modal-header">
      <h5 class="modal-title" id="exampleModalLabel">Create New Event</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
      <div class="modal-body">
        <%= render 'shared/error', object: event %>

        <div class="form-group">
          <%= f.file_field :cover, {class: 'form-control' }  %>
        </div>

        <% if f.object.cover.attached? %>
          <%= image_tag event.cover.url, size: "50x50" %>
        <% end %>

        <div class="form-group">
          <%= f.label :title, 'Event Title' %>
          <%= f.text_field :title, class: 'form-control', required: true %>
        </div>

        <div class="form-group">
          <%= f.label :description, ' Event Description' %>
          <%= f.text_area :description, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :price, 'Event Price' %>
          <%= f.text_field :price, class: 'form-control'%>
        </div>

        <div class="form-group">
          <%= f.label :location, 'Where' %>
          <%= f.text_field :location, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :start_at, 'Start Date/Time' %>
          <%= f.datetime_field :start_at, class: 'form-control', required: true, value: f.object.start_at&.strftime("%Y-%m-%dT%H:%M") %>
        </div>

        <div class="form-group">
          <%= f.label :end_at, 'End Date/Time(optional)' %>
          <%= f.datetime_field :end_at, class: 'form-control', value: f.object.end_at&.strftime("%Y-%m-%dT%H:%M") %>
        </div>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin_panel/events/_historical.html.erb
<table class="table table-borderless table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Event Name</th>
      <th scope="col">Start At</th>
      <th scope="col">Price</th>
      <th scope="col">Action</th>
    </tr>
  </thead>

  <tbody id="events-section">
    <% events.each do |event| %>
      <%= render 'admin_panel/events/event', event: event %>
    <% end %>
  </tbody>
</table>

<div id="historical-events-pagination">
  <%= paginate events, remote: true, param_name: :historical_events_page %>
</div>

app/views/admin_panel/events/_upcoming.html.erb
<table class="table table-borderless table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Event Name</th>
      <th scope="col">Start At</th>
      <th scope="col">Price</th>
      <th scope="col">Action</th>
    </tr>
  </thead>

  <tbody id="events-section">
    <% events.each do |event| %>
      <%= render 'admin_panel/events/event', event: event %>
    <% end %>
  </tbody>
</table>

<div id="upcoming-events-pagination">
  <%= paginate events, remote: true, param_name: :upcoming_events_page %>
</div>

app/views/admin_panel/events/create.js.erb
<% if @event.save %>
  $("#event-modal").modal('hide');
  $("#events-section").append("<%= j render 'admin_panel/events/event', event: @event %>");
  toastr.success('Event is successfully created.');
<% else %>
  $("#event-modal").html("<%= j render 'admin_panel/events/form', event: @event %>");
<% end %>

app/views/admin_panel/events/destroy.js.erb
<% if @event.destroy %>
  $("#<%= dom_id(@event) %>" ).remove();
  toastr.success('Event deleted successfully.');
<% else %>
  toastr.error("<%= @event.errors.full_messages.to_sentence %>");
<% end %>

app/views/admin_panel/events/edit.js.erb
$("#event-modal").html("<%= j render 'admin_panel/events/form', event: @event %>");
$("#event-modal").modal();

app/views/admin_panel/events/index.html.erb
<div class="row">
  <div class="container-fluid">
    <div class="search-bar">
      <div class="top-heading">
        <h1>Events</h1>
        <h6 class="mt-0">View and edit Events</h6>
      </div>
      <div class="d-flex justify-content-end">
        <%= link_to 'Create Event', new_admin_panel_event_path, remote: true, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>

<ul class="nav nav-pills mb-4 mt-3" id="events-tab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="upcoming-events-tab" data-toggle="pill" href="#upcoming-events" role="tab" aria-controls="upcoming-events" aria-selected="true">Upcoming</a>
  </li>

  <li class="nav-item">
    <a class="nav-link" id="historical-events-tab" data-toggle="pill" href="#historical-events" role="tab" aria-controls="historical-events" aria-selected="false">Historical</a>
  </li>
</ul>

<div class="tab-content" id="events-tabContent">
  <div class="tab-pane fade show active" id="upcoming-events" role="tabpanel" aria-labelledby="upcoming-events-tab">
    <%= render 'admin_panel/events/upcoming', events: @upcoming_events %>
  </div>

  <div class="tab-pane fade" id="historical-events" role="tabpanel" aria-labelledby="historical-events-tab">
    <%= render 'admin_panel/events/historical', events: @historical_events %>
  </div>
</div>

<div class="modal fade" id="event-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"></div>

app/views/admin_panel/events/index.js.erb
$("#upcoming-events").html("<%= j render('admin_panel/events/upcoming', events: @upcoming_events) %>");
$("#upcoming-events-pagination").html("<%= j(paginate(@upcoming_events, remote: true, param_name: :upcoming_events_page)) %>");

$("#historical-events").html("<%= j render('admin_panel/events/historical', events: @historical_events) %>");
$("#historical-events-pagination").html("<%= j paginate(@historical_events, remote: true, param_name: :historical_events_page) %>");

app/views/admin_panel/events/new.js.erb
$("#event-modal").html("<%= j render 'admin_panel/events/form', event: @event %>");
$("#event-modal").modal('show');

app/views/admin_panel/events/update.js.erb
<% if @event.save %>
  $("#event-modal").modal('hide');
  toastr.success('Event is successfully update.');
  $("#<%= dom_id(@event) %>" ).replaceWith( "<%= j render 'admin_panel/events/event', event: @event %>" );
<% else %>
  $("#event-modal").html("<%= j render 'admin_panel/events/form', event: @event %>");
<% end %>